version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'source-map-loader'
      - dependency-name: 'ts-loader'
      - dependency-name: 'typescript'
        versions: ['4.x']
      - dependency-name: 'webpack'
      - dependency-name: 'webpack-cli'
      - dependency-name: 'webpack-dev-server'
